Repository ssu-capstone-Itinera/server, pull requests merged in 2025-05, with the labels that each got.

#72 mypage 조회 기능 구현
  src/main/java/com/travel/domain/follow/dao/FollowRepository.java
  src/main/java/com/travel/domain/follow/service/FollowService.java
  src/main/java/com/travel/domain/member/api/MemberController.java
  src/main/java/com/travel/domain/member/dto/response/ProfileResponse.java
  src/main/java/com/travel/domain/member/entity/Member.java
  src/main/java/com/travel/domain/member/service/MemberService.java
  src/main/java/com/travel/domain/place/dto/RecommendationRequest.java
  src/main/java/com/travel/domain/post/post/dao/PostLikeRepository.java
  src/main/java/com/travel/domain/post/post/dao/PostRepository.java
  src/main/java/com/travel/domain/post/post/domain/Post.java
  src/main/java/com/travel/domain/post/service/PostLikeService.java
  src/main/java/com/travel/domain/post/service/PostService.java
  src/main/java/com/travel/domain/trip/dao/TripRepository.java
  src/main/java/com/travel/domain/trip/service/TripService.java
Labels: ✨feat

#73 place field 수정
  src/main/java/com/travel/domain/place/entity/Place.java
Labels: 🔧enhance, ♻️ refactor

#74 field 수정
  src/main/java/com/travel/domain/post/post/domain/Post.java
  src/main/java/com/travel/domain/trip/entity/Trip.java
Labels: ♻️ refactor

#75 tripresponse 생성
  src/main/java/com/travel/domain/member/dto/response/ProfileResponse.java
  src/main/java/com/travel/domain/trip/dto/response/TripResponse.java
  src/main/java/com/travel/domain/trip/service/TripService.java
Labels: ✨feat

#76 postresponse 생성
  src/main/java/com/travel/domain/member/dto/response/ProfileResponse.java
  src/main/java/com/travel/domain/member/service/MemberService.java
  src/main/java/com/travel/domain/post/post/service/PostLikeService.java
  src/main/java/com/travel/domain/post/post/service/PostService.java
  src/main/java/com/travel/domain/post/service/PostLikeService.java
Labels: ✨feat

#77 postresponse 생성
  src/main/java/com/travel/domain/post/post/dto/response/PostLikeResponse.java
  src/main/java/com/travel/domain/post/post/dto/response/PostResponse.java
Labels: ✨feat

#79 postresponse에 id 항목 추가
  src/main/java/com/travel/domain/post/post/dto/response/PostResponse.java
Labels: 🔧enhance, ✨feat

#81 cafe tag 추가
  src/main/java/com/travel/domain/placetype/entity/cafe/CafeDoc.java
  src/main/java/com/travel/domain/placetype/entity/cafe/CafeTag.java
Labels: ✨feat

#83 follow 기능 구현
  src/main/java/com/travel/domain/follow/api/FollowController.java
  src/main/java/com/travel/domain/follow/dao/FollowRepository.java
  src/main/java/com/travel/domain/follow/dto/FollowResponse.java
  src/main/java/com/travel/domain/follow/entity/Follow.java
  src/main/java/com/travel/domain/follow/service/FollowService.java
  src/main/java/com/travel/global/common/error/ErrorCode.java
Labels: ✨feat

#84 follow 함수 이름 변경
  src/main/java/com/travel/domain/follow/service/FollowService.java
  src/main/java/com/travel/domain/member/service/MemberService.java
Labels: ✨feat

#88 place api 파라미터 수정
  src/main/java/com/travel/domain/place/api/PlaceController.java
Labels: ♻️ refactor

#89 place api 수정
  src/main/java/com/travel/domain/place/api/PlaceController.java
Labels: ♻️ refactor

#90 PlaceDetailResponse 수정
  src/main/java/com/travel/domain/place/dto/PlaceDetailResponse.java
Labels: ♻️ refactor

#91 placetype response 수정
  src/main/java/com/travel/domain/placetype/dto/response/RestaurantResponse.java
  src/main/java/com/travel/domain/placetype/dto/response/TourattractionResponse.java
Labels: ♻️ refactor

#93 follow service 수정
  src/main/java/com/travel/domain/follow/service/FollowService.java
  src/main/java/com/travel/domain/member/service/MemberService.java
Labels: ♻️ refactor

#94 refactoring
  src/main/java/com/travel/domain/datapipeline/google/api/DatapipelineController.java
  src/main/java/com/travel/domain/member/dto/response/ProfileResponse.java
  src/main/java/com/travel/domain/post/post/domain/Post.java
  src/main/java/com/travel/domain/post/post/dto/response/UserPostListResponse.java
  src/main/java/com/travel/global/config/ElasticsearchConfig.java
Labels: ♻️ refactor

#96 post 모듈 생성
  src/main/java/com/travel/domain/placetype/entity/tourattraction/TourAttraction.java
  src/main/java/com/travel/domain/post/post/api/PostController.java
  src/main/java/com/travel/domain/post/post/dto/request/PostRequest.java
  src/main/java/com/travel/domain/post/post/dto/response/PostResponse.java
  src/main/java/com/travel/domain/post/post/service/PostService.java
Labels: ✨feat

#97 FollowService 오류 수정
  src/main/java/com/travel/domain/follow/service/FollowService.java
Labels: 🐛 bug

#98 PostService 오류 수정
  src/main/java/com/travel/domain/post/post/service/PostService.java
Labels: 🐛 bug

#99 Post 기능 일부 구현
  src/main/java/com/travel/domain/member/dto/response/ProfileResponse.java
  src/main/java/com/travel/domain/member/service/MemberService.java
  src/main/java/com/travel/domain/post/comment/dao/PostCommentRepository.java
  src/main/java/com/travel/domain/post/post/api/PostController.java
  src/main/java/com/travel/domain/post/post/dao/PostLikeRepository.java
  src/main/java/com/travel/domain/post/post/dao/PostRepository.java
  src/main/java/com/travel/domain/post/post/domain/Post.java
  src/main/java/com/travel/domain/post/post/domain/PostLike.java
  src/main/java/com/travel/domain/post/post/dto/request/PostRequest.java
  src/main/java/com/travel/domain/post/post/dto/response/PostDetailResponse.java
  src/main/java/com/travel/domain/post/post/dto/response/PostLikeResponse.java
  src/main/java/com/travel/domain/post/post/dto/response/PostResponse.java
  src/main/java/com/travel/domain/post/post/service/PostLikeService.java
  src/main/java/com/travel/domain/post/post/service/PostService.java
  src/main/java/com/travel/domain/trip/dao/TripRepository.java
  src/main/java/com/travel/domain/trip/dto/response/TripResponse.java
  src/main/java/com/travel/domain/trip/entity/Trip.java
  src/main/java/com/travel/domain/trip/service/TripService.java
  src/main/java/com/travel/global/common/error/ErrorCode.java
Labels: ✨feat

#100 userpostLikeResponse push
  src/main/java/com/travel/domain/post/post/domain/Post.java
  src/main/java/com/travel/domain/post/post/dto/response/UserPostLikeResponse.java
Labels: ✨feat

#101 getter 애너테이션 추가
  src/main/java/com/travel/domain/post/post/dto/response/PostDetailResponse.java
Labels: ♻️ refactor

#103 자체 로그인 기능 구현
  src/main/java/com/travel/domain/follow/service/FollowService.java
  src/main/java/com/travel/domain/member/dao/MemberRepository.java
  src/main/java/com/travel/domain/member/dto/MemberDto.java
  src/main/java/com/travel/domain/member/entity/Member.java
  src/main/java/com/travel/domain/member/entity/Provider.java
  src/main/java/com/travel/domain/member/service/MemberService.java
  src/main/java/com/travel/global/common/error/ErrorCode.java
  src/main/java/com/travel/global/config/WebSecurityConfig.java
  src/main/java/com/travel/global/security/JwtAuthenticationFilter.java
  src/main/java/com/travel/global/util/JwtUtil.java
  src/main/java/com/travel/security/auth/dto/CustomUserInfo.java
  src/main/java/com/travel/security/auth/dto/KakaoUserInfo.java
  src/main/java/com/travel/security/auth/dto/UserInfo.java
  src/main/java/com/travel/security/auth/dto/request/LoginRequest.java
  src/main/java/com/travel/security/auth/dto/request/RefreshTokenRequest.java
  src/main/java/com/travel/security/auth/dto/request/SignupRequest.java
  src/main/java/com/travel/security/auth/oauth/Oauth2Factory.java
  src/main/java/com/travel/security/auth/service/AuthService.java
  src/main/java/com/travel/security/auth/service/CustomAuthService.java
  src/main/java/com/travel/security/auth/service/CustomUserDetailsService.java
Labels: ✨feat

#104 자체 로그인 기능 구현
  src/main/java/com/travel/security/auth/api/AuthController.java
Labels: ✨feat

#106 MyPlace기능 구현
  src/main/java/com/travel/domain/place/api/PlaceController.java
  src/main/java/com/travel/domain/place/dto/MyPlaceRequest.java
  src/main/java/com/travel/domain/place/dto/MyPlaceResponse.java
  src/main/java/com/travel/domain/place/dto/PlaceDetailResponse.java
  src/main/java/com/travel/domain/place/service/PlaceGoogleService.java
  src/main/java/com/travel/domain/place/service/PlaceService.java
  src/main/java/com/travel/global/common/error/ErrorCode.java
Labels: ✨feat

#109 place service 오류 수정
  src/main/java/com/travel/domain/place/dto/PlaceDetailResponse.java
  src/main/java/com/travel/domain/place/service/PlaceService.java
Labels: 🐛 bug

#111 refactoring
  src/main/java/com/travel/domain/datapipeline/google/api/DatapipelineController.java
  src/main/java/com/travel/domain/datapipeline/google/service/DatapipelineService.java
  src/main/java/com/travel/domain/datapipeline/google/service/GoogleService.java
  src/main/java/com/travel/domain/place/api/PlaceController.java
Labels: ♻️ refactor

#113 document에 address 값 추가
  src/main/java/com/travel/domain/placetype/entity/cafe/CafeDoc.java
  src/main/java/com/travel/domain/placetype/entity/restaurant/RestaurantDoc.java
  src/main/java/com/travel/domain/placetype/entity/tourattraction/TourattractionDoc.java
Labels: 🔧enhance, ✨feat

#114 lat,lng 가져오는 함수 추가
  src/main/java/com/travel/domain/place/dto/PlaceCoordinate.java
  src/main/java/com/travel/domain/place/dto/RecommendationRequest.java
  src/main/java/com/travel/domain/place/service/PlaceGoogleService.java
  src/main/java/com/travel/domain/place/service/PlaceService.java
Labels: ✨feat

#116 cursorResponse 기능 구현
  build.gradle
  src/main/java/com/travel/domain/place/dao/PlaceRepository.java
  src/main/java/com/travel/domain/place/dao/PlaceRepositoryCustom.java
  src/main/java/com/travel/domain/place/dao/PlaceRepositoryImpl.java
  src/main/java/com/travel/domain/post/comment/domain/PostComment.java
  src/main/java/com/travel/domain/post/post/api/PostController.java
  src/main/java/com/travel/global/common/response/CursorPageResponse.java
  src/main/java/com/travel/global/config/QueryDslConfig.java
Labels: ✨feat

#117 cors 포트 추가
  src/main/java/com/travel/global/config/WebConfig.java
Labels: ♻️ refactor

#121 place responce format 변경
  src/main/java/com/travel/domain/place/api/PlaceController.java
  src/main/java/com/travel/domain/place/service/PlaceService.java
  src/main/java/com/travel/domain/placetype/dto/response/CafeResponse.java
  src/main/java/com/travel/domain/placetype/dto/response/RestaurantResponse.java
Labels: 🔧enhance, ♻️ refactor

#122 place responce format 변경
  src/main/java/com/travel/domain/place/dto/PlaceListResponse.java
  src/main/java/com/travel/domain/place/dto/PlaceResponse.java
Labels: 🔧enhance, ♻️ refactor

#126 placeResponse placeId 필드명 수정
  src/main/java/com/travel/domain/place/dto/PlaceResponse.java
Labels: ♻️ refactor

#129 getcafeTags 함수 연결
  src/main/java/com/travel/domain/datapipeline/google/service/DatapipelineService.java
  src/main/java/com/travel/domain/place/service/PlaceGoogleService.java
  src/main/java/com/travel/domain/place/service/PlaceService.java
Labels: ♻️ refactor

#134 refactoring
  src/main/java/com/travel/domain/datapipeline/google/service/DatapipelineService.java
  src/main/java/com/travel/domain/datapipeline/google/service/LLMService.java
  src/main/java/com/travel/domain/datapipeline/llm/entity/Prompt.java
  src/main/java/com/travel/domain/datapipeline/llm/service/GeminiService.java
  src/main/java/com/travel/domain/place/service/PlaceService.java
  src/main/java/com/travel/domain/placetype/dao/tourattraction/TourattractionRepositoryCustom.java
  src/main/java/com/travel/domain/placetype/dao/tourattraction/TourattractionRepositoryImpl.java
  src/main/java/com/travel/domain/placetype/entity/tourattraction/SubjectiveTag.java
Labels: ♻️ refactor

#139 tag 수정
  src/main/java/com/travel/domain/datapipeline/google/service/GoogleService.java
  src/main/java/com/travel/domain/placetype/entity/cafe/CafeTag.java
  src/main/java/com/travel/domain/placetype/entity/restaurant/RestaurantType.java
  src/main/java/com/travel/domain/placetype/entity/tourattraction/SubjectiveTag.java
  src/main/java/com/travel/domain/placetype/entity/tourattraction/TourattractionTag.java
Labels: ♻️ refactor

#142 UserPostListResponse TripResponse 변경
  src/main/java/com/travel/domain/post/post/dto/response/UserPostListResponse.java
  src/main/java/com/travel/domain/post/post/service/PostService.java
Labels: ♻️ refactor

#145 cafeTag 수정
  src/main/java/com/travel/domain/placetype/entity/cafe/CafeTag.java
Labels: 🐛 bug

#146 cafeTag 수정
  src/main/java/com/travel/domain/placetype/entity/cafe/CafeTag.java
Labels: ♻️ refactor

#147 mainPlaces로 수정
  src/main/java/com/travel/domain/trip/dto/request/TripSaveRequest.java
  src/main/java/com/travel/domain/trip/service/TripService.java
Labels: ♻️ refactor

#148 place save 중복 저장 방지
  src/main/java/com/travel/domain/datapipeline/google/service/DatapipelineService.java
Labels: ♻️ refactor

#149 docker-compose.yml 수정
  docker-compose.yml
Labels: ♻️ refactor

#152 docker-compose.yml 수정
  docker-compose.yml
Labels: 🐛 bug, ♻️ refactor

#154 tourattraction placeGoogleId 중복 방지
  src/main/java/com/travel/domain/place/service/PlaceService.java
Labels: ♻️ refactor
